from uc3m_money.storage.json_store import JsonStore
from uc3m_money.account_management_config import DEPOSITS_STORE_FILE
from uc3m_money.account_management_exception import AccountManagementException

class DepositsJsonStore(JsonStore):
 _file_label = DEPOSITS_STORE_FILE